services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=1234'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
    volumes:
      - ./docker/mysql:/var/lib/mysql

volumes:
  mysql-data:
